### ISSUE TITLE
Create a way to mask the output of model to eliminate illegal moves

### ISSUE THREAD

**Issue by jmvantreeck** [OnlyUseMeRocket/auto-catan#35]
![image](https://github.com/user-attachments/assets/71183a1a-803f-4f38-a7d3-4e48631c1d42)
Apply this logic to the policy_net output, such that we return a probability (softmax?) instead of just grabbing the largest Q value from the policy
![image](https://github.com/user-attachments/assets/bed864a9-8439-4c3a-9075-7bda367286dd)
![image](https://github.com/user-attachments/assets/c980c361-b873-4f70-abb1-8b75cd8090cc)

**Comment by dreyesol** [comment]
Merged to main in #42
