### ISSUE TITLE
Policy gets stuck trying to save lumber when it needs to discard resources

### ISSUE THREAD

**Issue by jmvantreeck** [OnlyUseMeRocket/auto-catan#43]
Two options: 
 - rather than select keep, select discard to encourage making a decision and not getting stuck in a loop
 - Remove this part of the game, and randomly discard appropriate number of resources - makes game state-action space smaller. 
 
![image](https://github.com/user-attachments/assets/6e58558f-87e8-4d8b-aff2-a7288569aee6)

**Comment by dreyesol** [comment]
Will work on this tomorrow

**Comment by jmvantreeck** [comment]
Working on this today. I think I have to also update the Neural Net for the DQN since we are shrinking the action space

**Comment by jmvantreeck** [comment]
Removed all of Keep resources, but policy still has issues with road builder - likely due having to select two roads. Can either fix, remove, set probability to 0, or allow road builder dev card to build 1 road

**Comment by jmvantreeck** [comment]
removed road builder card in push to main.
