### ISSUE TITLE
Environment can't detect game is finished

### ISSUE THREAD

**Issue by jmvantreeck** [OnlyUseMeRocket/auto-catan#6]
is_finished never seems to return 1, so the game is played indefinitely. 
![image](https://github.com/user-attachments/assets/8694eb17-4fba-41b7-b75b-0d135e6f3656)

**Comment by dreyesol** [comment]
made it work! pushed to a different branch because I also removed wandb and not sure if we want to get rid of it
![image](https://github.com/user-attachments/assets/922b3cc1-6fb0-4a59-bade-5d99be7d482a)

**Comment by jmvantreeck** [comment]
added a function to convert action number to English, so we can evaluate game state.
The game is properly running for the most part
